
service:
    prop1: service-dev-prop1
    prop2: service-dev-prop2
    prop3: service-dev-prop3
spring:
    profiles:
        include: service
    datasource:
        name: dev
        url: jdbc:mysql://localhost:3306/sst?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: sst
        password: sst
