mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml
    # 实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.xiaojz.profile.repository.entity
    #  typeEnumsPackage: com.baomidou.springboot.entity.enums
    global-config:
        db-config:
            # 主键类型
            #AUTO(0, "数据库ID自增"),
            #INPUT(1, "用户输入ID"),
            #ID_WORKER(2, "全局唯一ID"),
            #UUID(3, "全局唯一ID"),
            #NONE(4, "该类型为未设置主键类型"),
            #ID_WORKER_STR(5, "字符串全局唯一ID");
            id-type: 5
            table-prefix: t_
            table-underline: true
            # 字段策略 0:"忽略判断", 1:"非 NULL 判断"), 2:"非空判断"（@Deprecated，已拆分成insert-strategy、update-strategy、select-strategy）
            # field-strategy: 1
            # 逻辑删除配置（下面3个配置）
            logic-delete-field: deleted  #全局逻辑删除字段值
            logic-delete-value: 1
            logic-not-delete-value: 0
            # 更新字段策略
            # IGNORED(0) 忽略判断，所有字段都更新和插入,
            # NOT_NULL(1) 非NULL判断，只更新和插入非NULL值,
            # NOT_EMPTY(2) 非空判断，只更新和插入非NULL值且非空字符串,
            # DEFAULT(3) 默认NOT_NULL,
            # NEVER(4);
            update-strategy: 1
    configuration:
        map-underscore-to-camel-case: true
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        druidLoginName: admin
        druidPassword: admin
        ##durid监控页面http://localhost/druid/
        druid:
            web-stat-filter:
                enabled: false
