server:
    port: 20000
spring:
    profiles:
        active: dev #application.xml中引用可以用active，application-YY.xml中引用必须用include
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
        deserialization:
            fail-on-unknown-properties: false
            accept-empty-string-as-null-object: true
        serialization:
            write-date-keys-as-timestamps: false
            fail-on-empty-beans: false
        parser:
            allow-comments: true
            allow-unquoted-field-names: true
            allow-single-quotes: true
            allow-backslash-escaping-any-character: true
            allow-non-numeric-numbers: true
            allow-numeric-leading-zeros: true
            allow-unquoted-control-chars: true
        generator:
            escape-non-ascii: false
